remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Deyaa Mohammed
logo: /assets/img/me.png
description: Tech enthusiast, software tester, and avid gamer. Driven by a passion for technology and a commitment to delivering exceptional software solutions./
[**Home**](deyaamohammed.github.io) - [**Projects**](deyaamohammed.github.io/projects) - [**Learning Journey**](deyaamohammed.github.io/learningjourney)
show_downloads: false
